---
title: "PJ's Oral Fixation"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# install.packages("tidyverse")
library(devtools)
install_github("jokergoo/ComplexHeatmap")
# install.packages("grid")
library(tidyverse)
library(knitr)
library(grid)
library(broom)
library(ComplexHeatmap)
```

# Tidy data up
```{r message=FALSE, warning=FALSE, paged.print=TRUE}
data <- read_csv("Raw Binary Output(AutoRecovered).csv")
data <- data[1:65,]
write_csv(data, "data.csv")


# metaData <- readxl::read_xlsx("Survey Data.xlsx")
# write_csv(metaData1, "metaData.csv")

```

# Import data
```{r}
data <- read_csv("data.csv")
metaDataParticipants <- read_csv("metaDataParticipants.csv")
# metaDataPhonemes <- read_csv("metaDataPhonemes.csv")

```

# ANOVA
```{r}
data %>% 
  select(corrTotal) %>% 
  bind_cols(metaDataParticipants %>% select(Music)) %>% 
  aov(data = ., formula = corrTotal ~ Music) %>% 
  tidy() %>% 
  kable()



data %>% 
  select(corrTotal) %>% 
  bind_cols(metaDataParticipants %>% select(EarTrain)) %>% 
  aov(data = ., formula = corrTotal ~ EarTrain)%>% 
  tidy()%>% 
  kable()

data %>% 
  select(corrTotal) %>% 
  bind_cols(metaDataParticipants %>% select(Multilingual, EFL)) %>% 
  aov(data = ., formula = corrTotal ~ Multilingual + EFL)%>% 
  tidy()%>% 
  kable()


data %>% 
  select(corrTotal) %>% 
  bind_cols(metaDataParticipants %>% select(Tinnitus)) %>% 
  aov(data = ., formula = corrTotal ~ Tinnitus)%>% 
  tidy()%>% 
  kable()
  
```

# Control vs Total

```{r}
data %>% 
  select(corrTotal, corrControl) %>% 
  mutate(corrTotal = corrTotal/187) %>% 
  mutate(corrControl = corrControl/5) %>% 
  cor() %>% 
  kable()
```



# Correlations

```{r}
cor_mat <- data %>% 
  select(corrTotal, corrJCH, corrFam, corrLmpp, corrGK, corrBP, corrDT, corrMmpp, corrFmpp, corrNonfam) %>% 
  # ggplot(aes(x = corrTotal, y = corrJCH))+
  # geom_point()
  cor() #%>% 

od = hclust(dist(cor_mat))$order
cor_mat = cor_mat[od, od]
nm = rownames(cor_mat)  

ComplexHeatmap::Heatmap(cor_mat, name = "foo", cell_fun = function(j, i, x, y, width, height, fill) {
    if (i < j)
    grid.text(sprintf("%.2f", cor_mat[i, j]), x, y, gp = gpar(fontsize = 10))
}, cluster_rows = FALSE, cluster_columns = FALSE)


# col_fun = circlize::colorRamp2(c(0.45, 1), c("blue", "red"))
# # `col = col_fun` here is used to generate the legend
# hm <- ComplexHeatmap::Heatmap(cor_mat, name = "correlation", col = col_fun, rect_gp = gpar(type = "none"), 
#     cell_fun = function(j, i, x, y, width, height, fill) {
#         grid.rect(x = x, y = y, width = width, height = height, gp = gpar(col = "grey", fill = NA))
#         if(i == j) {
#             grid.text(nm[i], x = x, y = y)
#         } else if(i > j) {
#             # grid.circle(x = x, y = y, r = abs(cor_mat[i, j])/2 * min(unit.c(width, height)), 
#             #     gp = gpar(fill = col_fun(cor_mat[i, j]), col = NA))
#             grid.draw(x = x, y = y, width = width, height = height, gp = gpar(fill = col_fun(cor_mat[i, j]), col = NA))
#         } else {
#             grid.text(sprintf("%.3f", cor_mat[i, j]), x, y, gp = gpar(fontsize = 8))
#         }
#     }, cluster_rows = FALSE, cluster_columns = FALSE,
#     show_row_names = FALSE, show_column_names = FALSE)
```
# Plot
```{r}
data %>% 
  select(corrCongruent, corrTotal) %>% 
  ggplot(aes(x = corrCongruent, y = corrTotal))+
  geom_point()+
  theme_classic()+
  xlab("Congruent Correlation")+
  ylab("Total")+
  labs(title = "My Title")
```

